### ISSUE TITLE
Remove single beat

### ISSUE THREAD

**Issue by hydroPhil** [hatsumatsu/108#1]
I would love to be able to remove a single beat in case I misplaced it. Now I can only delete the entire sequence.
Cheers

**Comment by hatsumatsu** [comment]
Thanks for contributing, really appreciate it. Removing notes would ideed be handy, even if the current limitations foster creativity and unexpected results ;-) ! I think I'd go for a shortcut based solution to keep it in line with the existing controls / UI. I'll check if a Cmd+Z / Undo-feature could be easily implemented.

**Comment by poomato** [comment]
Yes an undo button would be perfection, and maybe a save sequence to cookies?

**Comment by hatsumatsu** [comment]
@poomato there is an option to get a unique URL for your beat: `Share` > `Copy` ...

**Comment by hatsumatsu** [comment]
I just added the undo feature. Use the `Z` key to delete previously added steps.

**Comment by hydroPhil** [comment]
awesome, this almost makes it a tool for live music, because you can constantly add and remove things
